version: 2.1

orbs:
  node: circleci/node@5.1.0

defaults: &defaults
  docker:
    - image: cimg/python:3.11.1
  working_directory: ~/project

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      
      - run:
          name: Instalar dependências Python
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Testar import da API (validação leve)
          command: |
            echo "from main import app" | python

      - run:
          name: Testar resposta da API local
          command: |
            uvicorn main:app --host 0.0.0.0 --port 8000 &
            sleep 5
            curl --fail http://localhost:8000 || (echo "API não respondeu" && exit 1)

  deploy:
    <<: *defaults
    steps:
      - checkout
      - node/install:
          node-version: '16.13'

      - run: node --version

      - run:
          name: Instalar Railway CLI
          command: npm install -g @railway/cli

      - run:
          name: Deploy via Railway CLI
          command: railway up --detach
          environment:
            RAILWAY_TOKEN: $RAILWAY_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
